services:
  app:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: ../../
    ports:
      - "3000:3000"
    volumes:
      - ../../src:/app/src
      - ../../package.json:/app/package.json
    env_file: .env.dev
  database:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:
