services:
  app:
    build:
      dockerfile: ./docker/migration/Dockerfile
      context: ../../
    env_file: .env.migration
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql/mysql-server
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:

networks:
  database:
